package com.excilys.formation.cdb.dao;

import static org.junit.Assert.*;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Optional;

import javax.persistence.NoResultException;

import org.junit.*;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.excilys.formation.cdb.configuration.TestPersistenceConfig;
import com.excilys.formation.cdb.exceptions.DaoException;
import com.excilys.formation.cdb.model.Company;
import com.excilys.formation.cdb.model.Computer;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = {TestPersistenceConfig.class})
public class ComputerDaoImplTest {
    
    static int NB_COMPUTER_IN_DB = 25;

    @Autowired
    ComputerDao computerDaoImpl;
    
    @BeforeClass
    public static void init() throws SQLException, ClassNotFoundException, IOException {
        Class.forName("org.hsqldb.jdbc.JDBCDriver");

        initDatabase();
    }

    @AfterClass
    public static void destroy() throws SQLException, ClassNotFoundException, IOException {
        try (Connection connection = getConnection(); Statement statement = connection.createStatement();) {
            statement.executeUpdate("DROP TABLE computer");
            statement.executeUpdate("DROP TABLE company");
            connection.commit();
        }
    }

    private static void initDatabase() throws SQLException {
        try (Connection connection = getConnection(); Statement statement = connection.createStatement();) {
            statement.execute("CREATE TABLE company (id bigint not null, name varchar(255), constraint pk_company primary key (id));");
            statement.execute("CREATE TABLE computer (id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 1) not null, name varchar(255), introduced datetime NULL, discontinued datetime NULL, company_id bigint default NULL, constraint pk_computer primary key (id));");
            connection.commit();
            for(int i = 0; i < NB_COMPUTER_IN_DB; i++) {
                statement.executeUpdate("insert into company (id,name) values (  "+i+",'company "+i+"');");
                statement.executeUpdate("insert into computer (id,name,company_id) values (  "+i+",'computer "+i+"', "+i+");");
            }
            connection.commit();
        }
    }

    private static Connection getConnection() throws SQLException {
        return DriverManager.getConnection("jdbc:hsqldb:mem:computer-database-db", "admincdb", "qwerty1234");
    }

    @Test
    public void listTest() throws DaoException {
        assertEquals(10, computerDaoImpl.list(0, 10, "id", false).size());
        assertEquals(NB_COMPUTER_IN_DB, computerDaoImpl.list(0, NB_COMPUTER_IN_DB, "id", false).size());
    }

    @Test
    public void readTest() throws DaoException {
        Computer computerExpected = null;
        Computer computerRead = null;
        for(int i = 0; i < NB_COMPUTER_IN_DB; i++) {
            computerExpected = new Computer(i, "computer "+i, null, null, new Company(i, "company "+i));
            computerRead = computerDaoImpl.read(i).get();

            assertEquals(computerExpected.getId(), computerRead.getId());
            assertEquals(computerExpected.getName(), computerRead.getName());
            assertEquals(computerExpected.getIntroduced(), computerRead.getIntroduced());
            assertEquals(computerExpected.getDiscontinued(), computerRead.getDiscontinued());
            assertEquals(computerExpected.getCompany().getId(), computerRead.getCompany().getId());
            assertEquals(computerExpected.getCompany().getName(), computerRead.getCompany().getName());
        }
    }

    @Test
    public void createTest() throws DaoException {
        Computer computer = new Computer(420000, "computer 420000", null, null, new Company(1, "company 1"));
        Computer computerCreated = computerDaoImpl.create(computer);

        assertEquals(computer.getId(), computerCreated.getId());
        assertEquals(computer.getName(), computerCreated.getName());
        assertEquals(computer.getIntroduced(), computerCreated.getIntroduced());
        assertEquals(computer.getDiscontinued(), computerCreated.getDiscontinued());
        assertEquals(computer.getCompany().getId(), computerCreated.getCompany().getId());
        assertEquals(computer.getCompany().getName(), computerCreated.getCompany().getName());
        
        NB_COMPUTER_IN_DB++;
    }

    @Test
    public void updateTest() throws DaoException {
        Computer computer = new Computer(1, "computer 100", null, null, new Company(10, "company 10"));
        Computer computerUpdated = computerDaoImpl.update(computer);

        assertEquals(computer.getId(), computerUpdated.getId());
        assertEquals(computer.getName(), computerUpdated.getName());
        assertEquals(computer.getIntroduced(), computerUpdated.getIntroduced());
        assertEquals(computer.getDiscontinued(), computerUpdated.getDiscontinued());
        assertEquals(computer.getCompany().getId(), computerUpdated.getCompany().getId());
        assertEquals(computer.getCompany().getName(), computerUpdated.getCompany().getName());

        computer = new Computer(1, "computer 1", null, null, new Company(1, "company 1"));
        computerDaoImpl.update(computer);
    }

    @Test(expected = NoResultException.class)
    public void deleteTest() throws DaoException {
        computerDaoImpl.delete(5);
        NB_COMPUTER_IN_DB++;
        
        Optional<Computer> oc = computerDaoImpl.read(5);
    }

    @Test
    public void countTest() throws DaoException {
        assertEquals(NB_COMPUTER_IN_DB, computerDaoImpl.count());
    }

}
